# Generated by Django 5.0.7 on 2025-07-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('preferred_volunteer_role', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('lifecycle_stage', models.CharField(default='Lead', max_length=50)),
            ],
        ),
    ]
