# Generated by Django 5.2.5 on 2025-08-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="hubspot_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="volunteer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hubspot_id", None), _negated=True),
                fields=("hubspot_id",),
                name="unique_hubspot_id_when_not_null",
            ),
        ),
    ]
