# Generated by Django 5.2.4 on 2025-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_alter_volunteer_hubspot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(help_text="The volunteer's availability.", max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(help_text="The volunteer's email address. Must be unique.", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(help_text="The volunteer's first name.", max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='how_did_you_hear_about_us',
            field=models.CharField(blank=True, help_text='How the volunteer heard about the organization. Optional.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='hubspot_id',
            field=models.CharField(blank=True, help_text='Stores the HubSpot Contact ID after a volunteer is approved and synced.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(help_text="The volunteer's last name.", max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(help_text="The volunteer's phone number.", max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='preferred_volunteer_role',
            field=models.CharField(help_text="The volunteer's preferred role.", max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='The application status, used in the admin approval workflow.', max_length=10),
        ),
    ]
