# Generated by Django 5.2.5 on 2025-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0003_remove_volunteer_lifecycle_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
