# Generated by Django 5.2.5 on 2025-09-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "volunteer",
            "0003_alter_volunteer_availability_alter_volunteer_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="volunteer",
            name="unique_hubspot_id_when_not_null",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="hubspot_id",
        ),
    ]
