# Generated by Django 5.2.5 on 2025-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0004_volunteer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="hubspot_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
