# Generated by Django 5.2.5 on 2025-08-15 18:10

from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin', 'admin@example.com', 'adminpassword')

class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_volunteer_hubspot_id'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
