"""
API URL Configuration for the Volunteer App.

This module defines the URL patterns for the REST API endpoints related
to the Volunteer model. It uses Django REST Framework's DefaultRouter to
automatically generate the standard CRUD endpoints for the VolunteerViewSet.

The following custom and explicit routes are also defined:
- `/token/`: For obtaining a JWT access and refresh token pair.
- `/token/refresh/`: For refreshing an expired JWT access token.
- `/signup/`: A public endpoint for new volunteer signups.
- `/upload-csv/`: An admin-only endpoint for batch-uploading volunteers.
- `/volunteers/`: The base endpoint for the VolunteerViewSet (list, create).
- `/volunteers/{id}/`: Standard detail endpoints (retrieve, update, delete).
- `/volunteers/{id}/approve/`: Custom action to approve a volunteer.
- `/volunteers/{id}/reject/`: Custom action to reject a volunteer.
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import api_views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

# A router is used to automatically generate the URLs for a ViewSet.
router = DefaultRouter()
# Register the VolunteerViewSet with the router under the 'volunteers' endpoint.
router.register(r'volunteers', api_views.VolunteerViewSet, basename='volunteer')

# The urlpatterns list routes individual URLs to views.
urlpatterns = [
    # URLs for JWT authentication
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Public-facing URL for volunteer signups.
    path('signup/', api_views.VolunteerPublicCreateView.as_view(), name='volunteer-signup-api'),

    # Admin URL for bulk CSV upload.
    path('upload-csv/', api_views.VolunteerCSVUploadAPIView.as_view(), name='upload-csv'),

    # Include the URLs generated by the router. This must be last.
    path('', include(router.urls)),
]
